name: RetroArch

on: workflow_dispatch

permissions:
  contents: read

jobs:
  linux: # Smoketest build using most restrictive compiler and default options
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential libxkbcommon-dev libx11-xcb-dev zlib1g-dev libfreetype6-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev nvidia-cg-toolkit nvidia-cg-dev libavcodec-dev libsdl2-dev libsdl-image1.2-dev libxml2-dev yasm flatpak flatpak-builder
          mkdir repo
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Checkout source repo
        uses: actions/checkout@v3   
        with:
          repository: hilltop804/Retroarch   
          path: source
      - name: Configure
        run: ./source/configure
      - name: Build
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak-builder builddir --repo=repo --install-deps-from=flathub --install --force-clean ./Retroarch/org.libretro.RetroArch.json
      - name: Zip
        run: sudo zip repo.zip repo/ -r
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Retroarch
          path: repo.zip
